USE BDecommerce

SELECT NOM_CLIENTE AS NOME, DSC_ENDERECO_COBRANCA AS ENDERECO, NUM_TELEFONE AS TELEFONE 
FROM CLIENTE
UNION
SELECT NOM_FORNECEDOR AS FORNECEDOR, DSC_ENDERECO AS ENDERECO, NUM_TELEFONE AS TELEFONE_FORNECEDOR
FROM FORNECEDOR
ORDER BY NOME ASC


ALTER TABLE FORMA_PAGAMENTO
ADD IND_STATUS1 CHAR(1) DEFAULT 'S' NOT NULL

ALTER TABLE FORMA_PAGAMENTO
ALTER COLUMN IND_STATUS VARCHAR(1000) NULL
GO

SELECT * FROM FORMA_PAGAMENTO

SP_HELP FORMA_PAGAMENTO
GO

SELECT COD_CLIENTE, NOM_CLIENTE AS NOME_COMPLETO,
NUM_CPF_CNPJ AS CPF_CNPJ,
DSC_ENDERECO_COBRANCA, NUM_TELEFONE AS CELULAR
FROM CLIENTE
ORDER BY NOM_CLIENTE
GO

