CREATE DATABASE BDecommerce_erro

USE BDecommerce_erro
GO

CREATE TABLE FORMA_PAGAMENTO
(
[COD_FORMA_PAGAMENTO] [int] NOT NULL,
[DSC_FORMA_PAGAMENTO] [varchar](100) NOT NULL,
)

GO

CREATE TABLE ITEM_PEDIDO
(	NUM_PEDIDO INT NOT NULL,
	COD_ITEM_PEDIDO INT NOT NULL, 
	COD_SERVICO INT NOT NULL,
	QTD_SERVICO NUMERIC(2) NOT NULL,
	VLR_TOTAL_ITEM NUMERIC (10,2) NOT NULL,
)
GO

CREATE TABLE SERVICO
(	COD_SERVICO INT NOT NULL,
	COD_FORNECEDOR INT NOT NULL,
	DSC_SERVICO VARCHAR(500) NOT NULL,
	TIP_SERVICO VARCHAR(50) NOT NULL,
	VLR_SERVICO NUMERIC (10,2) NOT NULL
)
GO

CREATE TABLE PEDIDO
(	NUM_PEDIDO INT NOT NULL,
	COD_CLIENTE INT NOT NULL, 
	DATA_PEDIDO DATETIME NOT NULL,
	VLR_TOTAL_PEDIDO NUMERIC(10,2) NOT NULL,
	COD_FORMA_PAGAMENTO INT NOT NULL
)
GO

CREATE TABLE CLIENTE
(	COD_CLIENTE INT NOT NULL,
	NOM_CLIENTE VARCHAR(100) NOT NULL,
	NUM_CPF_CNPJ NUMERIC(15) NULL,
	DSC_ENDERECO_COBRANCA VARCHAR(1000) NOT NULL,
	NUM_TELEFONE NUMERIC(14) NOT NULL,
)
GO

CREATE TABLE FORNECEDOR 
(	COD_FORNECERDOR INT NOT NULL,
	NOM_FORNECEDOR VARCHAR(100) NOT NULL,
	NUM_CNPJ NUMERIC(15) NULL,
	DSC_ENDERECO VARCHAR(1000) NOT NULL,
	NUM_TELEFONE NUMERIC(14) NOT NULL,
)
GO

ALTER TABLE FORMA_PAGAMENTO
ADD CONSTRAINT PK_COD_FORMA_PAGAMENTO PRIMARY KEY (COD_FORMA_PAGAMENTO)
GO

ALTER TABLE PEDIDO
ADD CONSTRAINT PK_NUM_PEDIDO PRIMARY KEY (NUM_PEDIDO)
GO

ALTER TABLE SERVICO
ADD CONSTRAINT PK_COD_SERVICO PRIMARY KEY (COD_SERVICO)
GO

ALTER TABLE ITEM_PEDIDO
ADD CONSTRAINT PK_COD_ITEM_PEDIDO PRIMARY KEY (COD_ITEM_PEDIDO)
GO

ALTER TABLE ITEM_PEDIDO
ADD CONSTRAINT FK_NUM_PEDIDO FOREIGN KEY (NUM_PEDIDO)
REFERENCES PEDIDO
GO

ALTER TABLE ITEM_PEDIDO
ADD CONSTRAINT FK_COD_SERVICO FOREIGN KEY (COD_SERVICO)
REFERENCES SERVICO
GO

ALTER TABLE CLIENTE
ADD CONSTRAINT PK_COD_CLIENTE PRIMARY KEY (COD_CLIENTE)

ALTER TABLE FORNECEDOR
ADD CONSTRAINT PK_COD_FORNECERDOR PRIMARY KEY (COD_FORNECERDOR)
GO

ALTER TABLE SERVICO
ADD CONSTRAINT FK_COD_FORNECEDOR FOREIGN KEY (COD_FORNECEDOR)
REFERENCES FORNECEDOR
GO

ALTER TABLE PEDIDO
ADD CONSTRAINT FK_COD_CLIENTE FOREIGN KEY (COD_CLIENTE)
REFERENCES CLIENTE
GO

ALTER TABLE PEDIDO
ADD CONSTRAINT FK_COD_FORMA_PAGAMENTO FOREIGN KEY (COD_FORMA_PAGAMENTO)
REFERENCES FORMA_PAGAMENTO 
GO

USE BDecommerce_erro

INSERT INTO dbo.CLIENTE (COD_CLIENTE,NOM_CLIENTE,NUM_CPF_CNPJ,DSC_ENDERECO_COBRANCA,NUM_TELEFONE)
VALUES (1,'MARIA',00000000000,'RUA MARTIN LUMBRIA',99999999)
GO

INSERT INTO dbo.FORMA_PAGAMENTO (COD_FORMA_PAGAMENTO,DSC_FORMA_PAGAMENTO)
VALUES (2,'CARTÃO CRÉDITO')
GO
		
INSERT INTO dbo.FORNECEDOR (COD_FORNECERDOR,NOM_FORNECEDOR,NUM_CNPJ,DSC_ENDERECO,NUM_TELEFONE)
VALUES (1,'ITAU',11111111111111,'BARONESA',9999999999)
GO

INSERT INTO dbo.PEDIDO (NUM_PEDIDO,DATA_PEDIDO,VLR_TOTAL_PEDIDO,COD_FORMA_PAGAMENTO,COD_CLIENTE)
VALUES (0002,'02-02-2022',26.000,(SELECT COD_FORMA_PAGAMENTO FROM dbo.FORMA_PAGAMENTO),
(SELECT COD_CLIENTE FROM dbo.CLIENTE))

INSERT INTO dbo.ITEM_PEDIDO (NUM_PEDIDO,COD_ITEM_PEDIDO,COD_SERVICO,QTD_SERVICO,VLR_TOTAL_ITEM)
VALUES ((SELECT NUM_PEDIDO FROM PEDIDO),10001,(SELECT COD_SERVICO FROM SERVICO),10,100.00)
GO

INSERT INTO dbo.SERVICO (COD_SERVICO,COD_FORNECEDOR,DSC_SERVICO,TIP_SERVICO,VLR_SERVICO)
VALUES (65,(SELECT COD_FORNECERDOR FROM FORNECEDOR),'TROCA DE PECA','MÃO DE OBRA',35.000)
GO

