SELECT C.NOM_CLIENTE AS "NOME DO CLIENTE", P.NUM_PEDIDO AS PEDIDO,
P.DATA_PEDIDO AS "DATA DO PEDIDO",
P.VLR_TOTAL_PEDIDO
FROM CLIENTE C JOIN PEDIDO P
ON C.COD_CLIENTE = P.COD_CLIENTE
WHERE DATA_PEDIDO > '2020'
ORDER BY [NOME DO CLIENTE]

SELECT * FROM PEDIDO
GO

--NOM_FORNECEDOR, NUM_TELEFONE, DSC_SERVICO, TIP_SERVICO e VLR_SERVICO.
--alfabeticamente pelo nome do fornecedor e descendentemente pelo valor do serviço.
SELECT F.NOM_FORNECEDOR AS FORNECEDOR,
F.NUM_TELEFONE AS TELEFONE,
S.DSC_SERVICO AS DESCRICAO_SERVICO,
S.TIP_SERVICO AS TIPO, VLR_SERVICO
FROM FORNECEDOR F LEFT JOIN SERVICO S
ON F.COD_FORNECERDOR = S.COD_FORNECEDOR
ORDER BY FORNECEDOR ASC, VLR_SERVICO DESC 
GO

