USE BDProducoes_TESTE

SELECT NOM_TITULO AS ORDENADOS_ALAFABETICAMENTE,UPPER (TIP_TITULO) AS TIPO_TITULO,
ANO_LANCAMENTO,QTD_MINUTOS,DSC_GENERO,CLASSIFICACAO_MEDIA,NOM_PESSOA
FROM TITULO, TITULO_DETALHE,AVALIACAO,PESSOA
WHERE IND_STATUS='A'
ORDER BY NOM_TITULO 

GO

