USE BDProducoes_TESTE

SP_HELP PESSOA

ALTER TABLE PESSOA 
ALTER COLUMN NOM_PESSOA VARCHAR(1000)

GO

ALTER TABLE TITULO ADD IND_STATUS CHAR(1) NULL 
GO

SELECT COD_TITULO, NOM_TITULO, IND_STATUS,

CASE IND_STATUS
WHEN 'A' THEN 'S'
ELSE 'N'
END AS DISPONIVEL
FROM TITULO 

GO
SELECT * FROM TITULO

USE BDProducoes_TESTE

BULK INSERT BDProducoes_TESTE.dbo.TITULO_DETALHE
FROM'D:\DOWNLOADS\TITULO_DETALHE.txt'
WITH ( FIELDTERMINATOR='\t',
		ROWTERMINATOR='\n',
		KEEPIDENTITY
     );

GO

SELECT COUNT(IND_STATUS)
FROM TITULO 
WHERE IND_STATUS='A' 

SELECT NOM_TITULO FROM TITULO
ORDER BY NOM_TITULO ASC
go

SELECT T.*,D.*
FROM TITULO T JOIN TITULO_DETALHE D 
ON T.COD_TITULO = D.COD_TITULO
ORDER BY T.NOM_TITULO
GO


 SELECT NOM_PRINCIPAL_TITULO, NOM_ORIGINAL_TITULO FROM TITULO_DETALHE
 ORDER BY NOM_PRINCIPAL_TITULO, NOM_ORIGINAL_TITULO ASC

 SELECT T.*,P.NOM_PESSOA AS "AUTOR",P2.NOM_PESSOA AS "DIRETOR"
 FROM TITULO T LEFT JOIN AUTORIA A
 ON T.COD_TITULO=A.COD_TITULO
 LEFT JOIN PESSOA P
 ON A.COD_PESSOA = P.COD_PESSOA
 LEFT JOIN DIRECAO D
 ON T.COD_TITULO = D.COD_TITULO
 LEFT JOIN PESSOA P2
 ON D.COD_PESSOA = P2.COD_PESSOA
 ORDER BY T.NOM_TITULO


 GO

 SELECT TOP 100 COD_TITULO, CLASSIFICACAO_MEDIA, QTD_VOTOS FROM AVALIACAO 

GO

 SELECT TOP(100) T.*,A.*
 FROM TITULO T JOIN AVALIACAO A 
 ON T.COD_TITULO=A.COD_TITULO
 ORDER BY A.CLASSIFICACAO_MEDIA DESC

 GO

 SP_HELP TITULO_DETALHE

 SELECT QTD_MINUTOS, DSC_GENERO FROM TITULO_DETALHE
 WHERE QTD_MINUTOS=0 OR DSC_GENERO='NULL' 	

 SELECT QTD_VOTOS FROM AVALIACAO
 WHERE QTD_VOTOS=0
 GO

 SELECT *
 FROM TITULO T JOIN AVALIACAO A
 ON T.COD_TITULO = A.COD_TITULO
 WHERE A.COD_TITULO IS NULL