CREATE DATABASE BDProducoes_TESTE
go

USE BDProducoes_TESTE;
go


CREATE TABLE dbo.TITULO
(	COD_TITULO INT NOT NULL,
	NOM_TITULO VARCHAR(1000) NULL,
);
GO

ALTER TABLE TITULO
	ADD CONSTRAINT PK_COD_TITULO PRIMARY KEY (COD_TITULO);
go

CREATE TABLE DIRECAO
(	COD_DIRECAO INT IDENTITY (1,1),
	COD_TITULO INT NOT NULL,
	COD_PESSOA INT NOT NULL,
); 
GO

ALTER TABLE DIRECAO
	ADD CONSTRAINT PK_COD_DIRECAO PRIMARY KEY (COD_DIRECAO);
ALTER TABLE DIRECAO 
	ADD CONSTRAINT FK_COD_TITULO FOREIGN KEY (COD_TITULO) REFERENCES TITULO;
GO
	
ALTER TABLE DIRECAO
	ADD CONSTRAINT FK_COD_PESSOA FOREIGN KEY (COD_PESSOA) REFERENCES PESSOA;

DROP TABLE PESSOA

CREATE TABLE PESSOA
(	COD_PESSOA INT NOT NULL,
	NOM_PESSOA VARCHAR(500) NOT NULL,
	ANO_NASCIMENTO INT NULL,
	ANO_FALESCIMENTO INT NULL,
	DSC_PROFISSAO VARCHAR(1000) NULL,
	PRIMARY KEY (COD_PESSOA),
);

CREATE TABLE TITULO_DETALHE
(	COD_TITULO INT NOT NULL,
	TIP_TITULO VARCHAR(100) NOT NULL,
	NOM_PRINCIPAL_TITULO VARCHAR(1000) NOT NULL,
	NOM_ORIGINAL_TITULO VARCHAR(1000) NOT NULL,
	IND_ADULTO BIT NOT NULL,
	ANO_LANCAMENTO INT NOT NULL,
	QTD_MINUTOS SMALLINT NULL,
	DSC_GENERO VARCHAR(1000) NULL,
);

GO

ALTER TABLE TITULO_DETALHE
	ADD CONSTRAINT FK_DETALHE_TITULO FOREIGN KEY (COD_TITULO) REFERENCES TITULO;

GO

DROP TABLE AVALIACAO

CREATE TABLE AVALIACAO
(	COD_TITULO INT NOT NULL,
	CLASSIFICACAO_MEDIA INT NOT NULL,
	QTD_VOTOS INT NOT NULL,
);

ALTER TABLE AVALIACAO
	ADD CONSTRAINT FK_AVALIACAO_TITULO FOREIGN KEY (COD_TITULO) REFERENCES TITULO;

	GO

CREATE TABLE AUTORIA 
(	COD_AUTORIA INT IDENTITY(1,1),
	COD_TITULO INT NOT NULL, 
	COD_PESSOA INT NOT NULL,
	PRIMARY KEY (COD_AUTORIA),
);

GO

 ALTER TABLE AUTORIA
	ADD CONSTRAINT FK_AUTORIA_TITULO FOREIGN KEY (COD_TITULO) REFERENCES TITULO;
	GO

ALTER TABLE AUTORIA
	ADD CONSTRAINT FK_AUTORIA_PESSOA FOREIGN KEY (COD_PESSOA) REFERENCES PESSOA;

GO

CREATE TABLE ELENCO
(	COD_ELENCO INT IDENTITY(1,1),
	COD_TITULO INT NOT NULL,
	COD_PESSOA INT NOT NULL, 
	DSC_FUNCAO VARCHAR(1000) NOT NULL,
	DESC_PERSONAGEM VARCHAR(1000) NULL,
	PRIMARY KEY (COD_ELENCO),
);

ALTER TABLE ELENCO
	ADD CONSTRAINT FK_ELENCO_TITULO FOREIGN KEY (COD_TITULO) REFERENCES TITULO

GO

ALTER TABLE ELENCO
	ADD CONSTRAINT FK_ELENCO_PESSOA FOREIGN KEY (COD_PESSOA) REFERENCES PESSOA

	




















	










	














